---
name: "Meta: Invalid Issue"

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: [ self-hosted, actions-runner ]
    steps:
      - uses: dessant/support-requests@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          support-label: invalid
          issue-comment: >
            :wave: @{issue-author}, please follow the template provided when new creating issues.
          close-issue: true
          lock-issue: true
          issue-lock-reason: resolved
