---
name: "Release: Schedule"

on:
  workflow_dispatch:
  schedule:
    # NOTE: The longest build for an app is ~1h30m
    # Keep this to run every 2 or more hours to prevent gremlins from spawning
    - cron: "0 */3 * * *"

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_PAT: ${{ secrets.GH_PAT }}

jobs:
  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetch.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ env.TOKEN }}

      - name: Install tools
        run: |
          sudo apt-get update 
          sudo apt-get -y install moreutils jo

      - name: Fetch new app versions
        id: fetch
        run: ./.github/scripts/fetch.sh    
        env:
          TOKEN: ${{ secrets.GH_PAT }} # not sure why we need the GH_PAT for this bit

  images-build:
    uses: geek-cookbook/containers/.github/workflows/action-image-build.yaml@main
    if: needs.generate-build-matrix.outputs.matrix != '[]'
    needs:
      - generate-build-matrix
    with:
      imagesToBuild: "${{ needs.generate-build-matrix.outputs.matrix }}"
      pushImages: "true"
      updateMetadata: "true"
      sendNotification: "true"
    secrets: inherit
